<?php
/**
 * Created by PhpStorm.
 * User: Heeseung
 * Date: 2015-01-12
 * Time: 오후 12:38
 */

namespace Trinity\Common\config;

use Illuminate\Support\ServiceProvider;

class TrinityServiceProvider extends ServiceProvider {
    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        // TODO: Implement register() method.
    }

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        \View::addNamespace('TrinityCommonView', __DIR__.'/../views/');
        \View::addNamespace('TrinityStudentView', __DIR__.'/../../Student/views/');
        \View::addNamespace('TrinityHrView', __DIR__.'/../../Hr/views/');
        \View::addNamespace('TrinityInstructorView', __DIR__.'/../../Instructor/views/');
        \View::addNamespace('TrinityConsultantView', __DIR__.'/../../Consultant/views/');
        \View::addNamespace('TrinityAdminView', __DIR__.'/../../Admin/views/');
    }

}